services:
  backend:
    image: python:3.12-slim
    container_name: fastapi-dev
    working_dir: /app

    ports:
      - "8000:8000"

    volumes:
      - .:/app          # editable code
      - venv:/opt/venv        # isolated python env

    environment:
      - VIRTUAL_ENV=/opt/venv
      - PATH=/opt/venv/bin:$PATH

    #user: "${UID}:${GID}"

    command: >
      sh -c "
        if [ ! -d /opt/venv/bin ]; then
          python -m venv /opt/venv;
        fi &&
        pip install --upgrade pip &&
        pip install -r requirements.txt &&
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "

volumes:
  venv: